services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: travel-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: travel-postgres
    environment:
      POSTGRES_DB: travel_booking_db
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel -d travel_booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: travel-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  booking-service:
    build:
      context: ./booking-service
    container_name: travel-booking-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_booking_db
      SPRING_DATASOURCE_USERNAME: travel
      SPRING_DATASOURCE_PASSWORD: travel
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"

  reservation-service:
    build:
      context: ./reservation-service
    container_name: travel-reservation-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8082:8082"

  notification-service:
    build:
      context: ./notification-service
    container_name: travel-notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_MAIL_ENABLED: true
      APP_MAIL_FROM: no-reply@travel-agency.local
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_SMTP_AUTH: false
      MAIL_SMTP_STARTTLS: false
    ports:
      - "8084:8084"
